### ISSUE TITLE
Do you want the contributor

### ISSUE THREAD

**Issue by sonulohani** [TakagiY/Ratatoskr-cpp#1]
Hi Takagiy,

I am a c++ dev and I am interested in working on your project. Do you want any contribution to your project or you want to be the sole owner of this project? Waiting for your reply. 

Thank you.

**Comment by takagiy** [comment]
Thank you for visiting this repository, @sonulohani .
Although this project is still baby, thus I may redesign its interface and structure frequently, but all issues or pull-requests are welcome.

I look forward to your reporting!

**Comment by TakagiY** [comment]
P.S. Almost sources are formated by clang-format-6.0.0, and it is my `.clang-format`:

```
AlwaysBreakTemplateDeclarations: true
CommentPragmas: ^
BreakBeforeBraces: Custom
BraceWrapping:
  BeforeElse: true
  BeforeCatch: true
NamespaceIndentation: Inner
```
